// Icon được phép dùng ngoài ds: chỉ import từ đây, không import lucide-react trực tiếp.
export {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BookOpen,
  Bot,
  Building2,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  Clock,
  Copy,
  ExternalLink,
  FileText,
  Folder,
  Globe,
  Inbox,
  Info,
  KeyRound,
  Languages,
  LayoutDashboard,
  ListChecks,
  Loader2,
  LogOut,
  Monitor,
  Moon,
  MoreHorizontal,
  Network,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Search,
  Settings,
  Sparkles,
  Star,
  Sun,
  Trash2,
  Users,
  X,
} from 'lucide-react';

import { type LucideProps, Star as StarOutline } from 'lucide-react';
import { createElement } from 'react';

/** Sao đặc (đã gắn sao); `Star` là dạng viền. */
export const StarFilled = (props: LucideProps) => createElement(StarOutline, { fill: 'currentColor', ...props });
